const room4Animations = {
    "resetke1": {
        "conditions": [],
        after: ["endGame"]    
    },
    "resetke2": {"conditions": []},
    "Wall.018Action": { conditions: [] },
    "initial_cell.001_cellAction": { conditions: [], isActive: true },
    "initial_cell.001_cell.001Action": { conditions: [], isActive: true },
    "initial_cell.001_cell.002Action": { conditions: [], isActive: true },
    "initial_cell.001_cell.003Action": { conditions: [], isActive: true },
    "initial_cell.001_cell.004Action": { conditions: [], isActive: true },
    "initial_cell.001_cell.005Action": { conditions: [], isActive: true },
    "initial_cell.001_cell.006Action": {conditions: [], isActive: true},
    "initial_cell.002Action": { conditions: [], isActive: true },
    "initial_cell.003_cellAction": { conditions: [], isActive: true },
    "initial_cell.003_cell.001Action": { conditions: [], isActive: true },
    "initial_cell.003_cell.002Action": { conditions: [], isActive: true },
    "initial_cell.003_cell.003Action": { conditions: [], isActive: true },
    "initial_cell.003_cell.004Action": { conditions: [], isActive: true },
    "initial_cell.003_cell.005Action": { conditions: [], isActive: true },
    "initial_cell.003_cell.006Action": { conditions: [], isActive: true },
    initial_cell_cellAction: { conditions: [], isActive: true },
    "initial_cell_cell.001Action": { conditions: [], isActive: true },
    "initial_cell_cell.002Action": { conditions: [], isActive: true },
    "initial_cell_cell.003Action": { conditions: [], isActive: true },
    "initial_cell_cell.004Action": { conditions: [], isActive: true },
    "Cube.070_cellAction": { conditions: [], isActive: true },
    "Cube.070_cell.003Action": { conditions: [], isActive: true },
    "Cube.070_cell.004Action": { conditions: [], isActive: true },
    "Cube.070_cell.006_cellAction": { conditions: [], isActive: true },
    "Cube.070_cell.006_cell.001Action": { conditions: [], isActive: true },
    "Cube.070_cell.006_cell.002Action": { conditions: [], isActive: true },
    "Cube.070_cell.006_cell.004Action": { conditions: [], isActive: true },
    "Cube.070_cell.006_cell.005Action": { conditions: [], isActive: true },
    "Cube.070_cell.007_cellAction": { conditions: [], isActive: true },
    "Cube.070_cell.007_cell.001Action": { conditions: [], isActive: true },
    "Cube.070_cell.007_cell.002Action": { conditions: [], isActive: true },
    "Cube.070_cell.007_cell.003Action": { conditions: [], isActive: true },
    "Cube.070_cell.007_cell.004Action": { conditions: [], isActive: true },
    "Cube.070_cell.007_cell.005Action": { conditions: [], isActive: true },
    "Cube.070_cell.007_cell.007Action": { conditions: [], isActive: true },
    "Cube.070_cell.008Action": { conditions: [], isActive: true },
    "Cube.070_cell.009_cellAction": { conditions: [], isActive: true },
    "Cube.070_cell.009_cell.001Action": { conditions: [], isActive: true },
    "Cube.070_cell.009_cell.002Action": { conditions: [], isActive: true },
    "Cube.070_cell.009_cell.003Action": { conditions: [], isActive: true },
    "Cube.070_cell.009_cell.005Action": { conditions: [], isActive: true },
    "Cube.075_cell.002Action": { conditions: [], isActive: true },
    "Cube.075_cell.003Action": { conditions: [], isActive: true },
    "Cube.075_cell.005_cellAction": { conditions: [], isActive: true },
    "Cube.075_cell.005_cell.001Action": { conditions: [], isActive: true },
    "Cube.075_cell.005_cell.003_cell.001Action": { conditions: [], isActive: true },
    "Cube.075_cell.005_cell.003_cell.003Action": { conditions: [], isActive: true },
    "Cube.075_cell.005_cell.003_cell.005Action": { conditions: [], isActive: true },
    "Cube.075_cell.005_cell.003_cell.006Action": { conditions: [], isActive: true },
    "Cube.075_cell.005_cell.003_cell.007Action": { conditions: [], isActive: true },
    "Cube.075_cell.005_cell.004Action": { conditions: [], isActive: true },
    "Cube.075_cell.005_cell.006Action": { conditions: [], isActive: true },
    "Cube.075_cell.005_cell.007Action": { conditions: [], isActive: true },
    "Cube.075_cell.006Action": { conditions: [], isActive: true },
    "Cube.075_cell_cellAction": { conditions: [], isActive: true },
    "Cube.075_cell_cell.001Action": { conditions: [], isActive: true },
    "Cube.075_cell_cell.002Action": { conditions: [], isActive: true },
    "Cube.075_cell_cell.003Action": { conditions: [], isActive: true },
    "Cube.075_cell_cell.004Action": { conditions: [], isActive: true },
    "Cube.075_cell_cell.005Action": { conditions: [], isActive: true },
    "Cube.075_cell_cell.006Action": { conditions: [], isActive: true },
    "Cube.075_cell_cell.007Action": { conditions: [], isActive: true },
    "Cube.076_cellAction": { conditions: [], isActive: true },
    "Cube.076_cell.001_cell.002Action": { conditions: [], isActive: true},
    "Cube.076_cell.001_cell.003Action": { conditions: [], isActive: true },
    "Cube.076_cell.001_cell.004Action": { conditions: [], isActive: true },
    "Cube.076_cell.002_cell.001Action": { conditions: [], isActive: true },
    "Cube.076_cell.002_cell.002Action": { conditions: [], isActive: true },
    "Cube.076_cell.002_cell.004Action": { conditions: [], isActive: true },
    "Cube.076_cell.002_cell.005Action": { conditions: [], isActive: true },
    "Cube.076_cell.004_cell.002Action": { conditions: [], isActive: true },
    "Cube.076_cell.004_cell.004Action": { conditions: [], isActive: true },
    "Cube.076_cell.004_cell.005Action": { conditions: [], isActive: true },
    "Cube.076_cell.004_cell.006Action": { conditions: [], isActive: true },
    "Cube.076_cell.004_cell.007Action": { conditions: [], isActive: true },
    floorfall: { conditions: [] },
    "Cube.076_cell.001_cell.007Action": { conditions: [], isActive: true },
    "Cube.076_cell.001_cell.008Action": { conditions: [], isActive: true },
    "Cube.076_cell.001_cell.009Action": { conditions: [], isActive: true },
    "Cube.076_cell.002_cell.006Action": { conditions: [], isActive: true },
    "Cube.076_cell.002_cell.007Action": { conditions: [], isActive: true },
    "Cube.076_cell.002_cell.009Action": { conditions: [], isActive: true },
    "Cube.076_cell.002_cell.010Action": { conditions: [], isActive: true },
    "Cube.076_cell.007Action": { conditions: [] },
    "Cube.076_cell.004_cell.009Action": { conditions: [], isActive: true },
    "Cube.076_cell.004_cell.011Action": { conditions: [], isActive: true },
    "Cube.076_cell.004_cell.012Action": { conditions: [], isActive: true },
    "Cube.076_cell.004_cell.013Action": { conditions: [], isActive: true },
    "Cube.076_cell.004_cell.014Action": { conditions: [], isActive: true },
    otvoritev: { conditions: [] },
  };
  
  export default room4Animations;
  