const room2Animations = {
  "initial_cell.001_cellAction": { conditions: ["breakStairs"] },
  "initial_cell.001_cell.001Action": { conditions: ["breakStairs"] },
  "initial_cell.001_cell.002Action": { conditions: ["breakStairs"] },
  "initial_cell.001_cell.003Action": { conditions: ["breakStairs"] },
  "initial_cell.001_cell.004Action": { conditions: ["breakStairs"] },
  "initial_cell.001_cell.005Action": { conditions: ["breakStairs"] },
  "initial_cell.001_cell.006Action": { conditions: ["breakStairs"] },
  "initial_cell.002Action": { conditions: ["breakStairs"] },
  "initial_cell.003_cellAction": { conditions: ["breakStairs"] },
  "initial_cell.003_cell.001Action": { conditions: ["breakStairs"] },
  "initial_cell.003_cell.002Action": { conditions: ["breakStairs"] },
  "initial_cell.003_cell.003Action": { conditions: ["breakStairs"] },
  "initial_cell.003_cell.004Action": { conditions: ["breakStairs"] },
  "initial_cell.003_cell.005Action": { conditions: ["breakStairs"] },
  "initial_cell.003_cell.006Action": { conditions: ["breakStairs"] },
  initial_cell_cellAction: { conditions: ["breakStairs"] },
  "initial_cell_cell.001Action": { conditions: ["breakStairs"] },
  "initial_cell_cell.002Action": { conditions: ["breakStairs"] },
  "initial_cell_cell.003Action": { conditions: ["breakStairs"] },
  "initial_cell_cell.004Action": { conditions: ["breakStairs"] },
  "Cube.070_cellAction": { conditions: ["breakStairs"] },
  "Cube.070_cell.003Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.004Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.006_cellAction": { conditions: ["breakStairs"] },
  "Cube.070_cell.006_cell.001Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.006_cell.002Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.006_cell.004Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.006_cell.005Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.007_cellAction": { conditions: ["breakStairs"] },
  "Cube.070_cell.007_cell.001Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.007_cell.002Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.007_cell.003Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.007_cell.004Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.007_cell.005Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.007_cell.007Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.008Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.009_cellAction": { conditions: ["breakStairs"] },
  "Cube.070_cell.009_cell.001Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.009_cell.002Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.009_cell.003Action": { conditions: ["breakStairs"] },
  "Cube.070_cell.009_cell.005Action": { conditions: ["breakStairs"] },
  "Cube.075_cell.002Action": { conditions: ["breakStairs"] },
  "Cube.075_cell.003Action": { conditions: ["breakStairs"] },
  "Cube.075_cell.005_cellAction": { conditions: ["breakStairs"] },
  "Cube.075_cell.005_cell.001Action": { conditions: ["breakStairs"] },
  "Cube.075_cell.005_cell.003_cell.001Action": {
    conditions: ["breakStairs"],
  },
  "Cube.075_cell.005_cell.003_cell.003Action": {
    conditions: ["breakStairs"],
  },
  "Cube.075_cell.005_cell.003_cell.005Action": {
    conditions: ["breakStairs"],
  },
  "Cube.075_cell.005_cell.003_cell.006Action": {
    conditions: ["breakStairs"],
  },
  "Cube.075_cell.005_cell.003_cell.007Action": {
    conditions: ["breakStairs"],
  },
  "Cube.075_cell.005_cell.004Action": { conditions: ["breakStairs"] },
  "Cube.075_cell.005_cell.006Action": { conditions: ["breakStairs"] },
  "Cube.075_cell.005_cell.007Action": { conditions: ["breakStairs"] },
  "Cube.075_cell.006Action": { conditions: ["breakStairs"] },
  "Cube.075_cell_cellAction": { conditions: ["breakStairs"] },
  "Cube.075_cell_cell.001Action": { conditions: ["breakStairs"] },
  "Cube.075_cell_cell.002Action": { conditions: ["breakStairs"] },
  "Cube.075_cell_cell.003Action": { conditions: ["breakStairs"] },
  "Cube.075_cell_cell.004Action": { conditions: ["breakStairs"] },
  "Cube.075_cell_cell.005Action": { conditions: ["breakStairs"] },
  "Cube.075_cell_cell.006Action": { conditions: ["breakStairs"] },
  "Cube.075_cell_cell.007Action": { conditions: ["breakStairs"] },
  "Cube.076_cellAction": { conditions: ["breakStairs"] },
  "Cube.076_cell.001_cell.002Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.001_cell.003Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.001_cell.004Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.002_cell.001Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.002_cell.002Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.002_cell.004Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.002_cell.005Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.002Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.004Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.005Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.006Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.007Action": { conditions: ["breakStairs"] },
  floorfall: { conditions: ["breakStairs"] },
  "Cube.076_cell.001_cell.007Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.001_cell.008Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.001_cell.009Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.002_cell.006Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.002_cell.007Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.002_cell.009Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.002_cell.010Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.007Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.009Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.011Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.012Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.013Action": { conditions: ["breakStairs"] },
  "Cube.076_cell.004_cell.014Action": { conditions: ["breakStairs"] },
  "otvoritev": { after: "levelComplete" },
};

const room3Animations = {
  "Cube_cell.011Action": { "before": ["playSound"], soundName : "rocks-falling.mp3", "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.010Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.009Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.008Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.007Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.006Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.003Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.001Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.015Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.014Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.013Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.012Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.011Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.010Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.009Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.008Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.009Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.008Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.006Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.005Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.001Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.008Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.006Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.005Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.009Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.008Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.007Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.005Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.001Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.001Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.002Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.003Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.004Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.005Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.012Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.001Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.002Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.005Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.008Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.003Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.001Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.002Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.003Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.004Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.005Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.006Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.007Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.016Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.002Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.003Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.004Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.007Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.010Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.001Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.002Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.004Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.002Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.003Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.004Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.006Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.010Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.018Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.017Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.016Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.015Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.014Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.013Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.012Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.011Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.010Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.009Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.006Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.024Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.023Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.022Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.021Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.020Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.019Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.018Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.017Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.015Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.014Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.013Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.012Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.011Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.012Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.011Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.010Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.015Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.014Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.013Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.012Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.011Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.019Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.020Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.021Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.022Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.023Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.024Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.013Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.014Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.015Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.016Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.007Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.008Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.025Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.026Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.027Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.028Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.029Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.030Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.031Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.032Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.016Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.017Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.018Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.019Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.020Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.013Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.014Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.015Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.016Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.017Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.018Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.019Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.020Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.030Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.029Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.028Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.027Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.026Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.025Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.020Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.019Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.018Action": { "conditions": ["triggerParkourRocks"], isActive: true },
  "Cube_cell.007_cell.017Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.010Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.009Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.040Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.039Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.038Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.037Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.036Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.035Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.034Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.033Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.025Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.024Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.023Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.022Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.021Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.020Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.019Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.018Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.025Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.024Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.023Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.022Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.021Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.031Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.032Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.033Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.034Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.035Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.036Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.021Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.022Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.023Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.024Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.011Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.012Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.041Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.042Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.043Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.044Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.045Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.046Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.047Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.048Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.026Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.027Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.028Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.029Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.030Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.021Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.022Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.023Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.026Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.027Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.028Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.029Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.030Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.042Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.041Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.040Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.039Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.038Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.037Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.028Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.027Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.026Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.025Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.014Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.013Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.056Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.055Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.054Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.053Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.052Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.051Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.050Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.049Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.035Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.034Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.033Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.032Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.031Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.028Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.027Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.026Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.035Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.034Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.033Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.032Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.031Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.043Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.044Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.045Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.046Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.047Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.048Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.029Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.030Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.031Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.032Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.015Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.016Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.057Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.058Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.059Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.060Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.061Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.062Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.063Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.005_cell.064Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.036Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.037Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.038Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.039Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.004_cell.040Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.029Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.030Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.006_cell.002_cell.031Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.036Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.037Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.038Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.039Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Cube_cell.007_cell.004_cell.040Action": { "conditions": ["triggerParkourRocks"], isActive: true },
  "Sphere_cell.241_cell.003Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Sphere_cell.241_cell.001Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Sphere_cell.241_cell.002Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Sphere_cell.241_cell.004Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Sphere_cell.241_cell.005Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Sphere_cell.241_cell.006Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Sphere_cell.241_cell.007Action": { "conditions": ["triggerParkourRocks"], isActive: true }, "Sphere_cell.241_cell.008Action": { "conditions": ["triggerParkourRocks"], isActive: true },
  "waterAction.006": { loop: true },
  "Bone.001Action.002": { loop: true },
  "Bone.002Action": { loop: true },
  "Bone.003Action": { loop: true },
  "Bone.005Action": { loop: true }
}

export const scenes = {
  Room1: {
    name: "first_room",
    maxDuration: 90000,
    interactables: [
      { name: "Flashlight", type: "carry", carrying: true },
      { name: "Fuse", type: "carry", setConditions: { carry_fuse: true } },
      {
        name: "Fusebox",
        type: "interact",
        interact: {
          play: [
            "fusebox_open_action",
            "Fuse_upper_insert",
            "Fuse_lower_insert",
          ],
        },
      },
      {
        name: "Switch",
        type: "interact",
        interact: { play: ["HandleAnimation"] },
      },
      {
        name: "Invisible_openDoors",
        aabbEnabled: false,
        type: "interact",
        interact: { play: ["left_doorAction", "right_doorAction"] },
      },
    ],
    animations: {
      left_doorAction: {
        before: ["disableAABB", "disableInteractable"],
        disableInteractables: ["Invisible_openDoors"],
        disableNodes: ["left_door"],
      },
      right_doorAction: {
        before: ["disableAABB", "disableInteractable"],
        disableInteractables: ["Invisible_openDoors"],
        disableNodes: ["right_door"],
      },
      garage_open_action: { conditions: ["fuse_inserted"] }, // garage open
      fusebox_open_action: {
        conditions: ["!fusebox_open"],
        after: ["setCondition"],
        setConditions: { fusebox_open: true },
      }, // open fusebox
      Fuse_upper_insert: {
        before: ["disableInteractable"],
        disableInteractables: ["Fuse", "Fusebox"],
        conditions: ["carry_fuse", "fusebox_open", "!fuse_inserted"],
        after: ["setCondition"],
        setConditions: { fuse_inserted: true },
      },
      Fuse_lower_insert: {
        before: ["disableInteractable"],
        disableInteractables: ["Fuse", "Fusebox"],
        conditions: ["carry_fuse", "fusebox_open", "!fuse_inserted"],
        after: ["setCondition"],
        setConditions: { fuse_inserted: true },
      },
      HandleAnimation: {
        after: ["trigger", "resetAnimation"],
        trigger: ["garage_open_action"],
      },
    },
  },
  Room2: {
    name: "second_room",
    maxDuration: 60000,
    interactables: [
      { name: "Flashlight", type: "carry", carrying: true },
      {
        name: "Invisible_activate_floor_break",
        type: "interact",
        interact: { play: Object.keys(room2Animations) },
      },
    ],
    animations: room2Animations,
  },
  Room3: {
    maxDuration: 120000,
    name: "parkour_room",
    interactables: [{ name: "Flashlight", type: "carry", carrying: true }],
    animations: room3Animations
  },
};
